name: Tests

on: [push, pull_request]

jobs:
  my-job:
    name: Run MATLAB Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: matlab-actions/setup-matlab@v3
      - name: Run Tests
        uses: matlab-actions/run-command@v3
        with:
          command: run_checks